### PR TITLE
SW-11. code re-organization.

### PR DESCRIPTION
**Pull request by changtengfei**

### CODE REVIEW

**Comment by changtengfei** [comment]
This PR is still WIP. Please don't merge it for now

**Comment by lydia-lee** [comment]
Question about the separate modules: Is the plan to eventually have separate directories? That is, I see that the set_X_LDO_voltage() functions are all still contained within the scm3c_hw_interface.

**Comment by changtengfei** [comment]
I am still thinking about what is the right way to organize the scm3c_hw_interface part. 
Actually all the functions in the scm3c_hw_interface is setting the ASC directly or indirectly including the LDOs. So I put all those functions together in one place for now. 
I think it's not necessary to have each module one directory but if you say all modules in one directory, it sounds reasonable.

**Comment by changtengfei** [comment]
@lydia-lee this is PR is ready to merge for me. Could you review it? Thanks!

**Review by lydia-lee — APPROVED** [review]

**Pull request merged**
